export const GET_PRODUCTS = "GET_PRODUCTS"

export const SHOW_LOADER = "SHOW_LOADER"
export const HIDE_LOADER = "HIDE_LOADER"

export const ADD_PRODUCT_CART = "ADD_PRODUCT_CART"
export const CLEAR_CART = "CLEAR_CART"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const PLUS_CART_ITEM = "PLUS_CART_ITEM"
export const MINUS_CART_ITEM = "MINUS_CART_ITEM"


